stages:
  - test
  - build
  - deploy


test:
  stage: test

  variables:
    # Change pip's cache directory to be inside the project directory since we can
    # only cache local items.
    PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"
    # Elasticsearch service variables
    ES_JAVA_OPTS: "-Xms512m -Xmx512m"
    # Reporter config variables
    ES_HOST: elasticsearch-test
    AMQP_HOST: rabbitmq-test

  image: python:3.8.9-slim

  services:
    - name: rabbitmq:3.8.0-management
      alias: rabbitmq-test
    - name: elasticsearch:6.2.4
      alias: elasticsearch-test
      command: ["bin/elasticsearch", "-Ediscovery.type=single-node"]

  cache:
    paths:
      - .cache/pip
      - venv/

  # Pip's cache doesn't store the python packages
  # https://pip.pypa.io/en/stable/reference/pip_install/#caching
  #
  # If you want to also cache the installed packages, you have to install
  # them in a virtualenv and cache it as well.

  before_script:
    - python -V  # Print out python version for debugging
    - pip install virtualenv
    - virtualenv venv
    - source venv/bin/activate
    - pip install -r requirements-test.txt
    - pip install --no-cache-dir .

  script:
    - coverage run -m pytest tests
    - coverage report -m


build:
  stage: build
  only:
    - tags

  variables:
    IMAGE_TAG: ${CI_REGISTRY_IMAGE}:${CI_COMMIT_TAG}
    LATEST_TAG: ${CI_REGISTRY_IMAGE}:latest
    DOCKER_TLS_CERTDIR: ""

  image: docker

  services:
    - docker:dind

  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker info

  script:
    - docker build -t $IMAGE_TAG --no-cache .
    - docker tag $IMAGE_TAG $LATEST_TAG
    - docker push $IMAGE_TAG
    - docker push $LATEST_TAG
    - docker logout $CI_REGISTRY


.deploy:
  stage: deploy

  variables:
    CONTAINER_IMAGE: ${CI_REGISTRY_IMAGE}:${CI_COMMIT_TAG}

  image: ${TOOLS_IMAGE}:${TOOLS_TAG}

  before_script:
    - git clone https://oauth2:${GITLAB_ACCESS_TOKEN}@${GITLAB_HOST}/${MANIFESTS_NAMESPACE}/k8s-manifests.git

  script:
    - sed -i "s#<DOCKER_IMAGE>#${CONTAINER_IMAGE}#g" k8s-manifests/amqp-reporting/deployment-es.yaml
    - sed -i "s#<DOCKER_IMAGE>#${CONTAINER_IMAGE}#g" k8s-manifests/amqp-reporting/deployment-smtp.yaml
    - sed -i "s#<CI_ENVIRONMENT_SLUG>#${CI_ENVIRONMENT_SLUG}#g" k8s-manifests/amqp-reporting/deployment-es.yaml
    - sed -i "s#<CI_ENVIRONMENT_SLUG>#${CI_ENVIRONMENT_SLUG}#g" k8s-manifests/amqp-reporting/deployment-smtp.yaml
    - kubectl apply -f k8s-manifests/amqp-reporting/deployment-es.yaml
    - kubectl annotate deployment amqp-es-reporter-bacteria kubernetes.io/change-cause="Update to ${CI_COMMIT_TAG}"
    - kubectl annotate deployment amqp-es-reporter-metazoa kubernetes.io/change-cause="Update to ${CI_COMMIT_TAG}"
    - kubectl annotate deployment amqp-es-reporter-microbes kubernetes.io/change-cause="Update to ${CI_COMMIT_TAG}"
    - kubectl annotate deployment amqp-es-reporter-plants kubernetes.io/change-cause="Update to ${CI_COMMIT_TAG}"
    - kubectl annotate deployment amqp-es-reporter-production kubernetes.io/change-cause="Update to ${CI_COMMIT_TAG}"
    - kubectl annotate deployment amqp-es-reporter-rapid kubernetes.io/change-cause="Update to ${CI_COMMIT_TAG}"
    - kubectl annotate deployment amqp-es-reporter-vert kubernetes.io/change-cause="Update to ${CI_COMMIT_TAG}"
    - kubectl annotate deployment amqp-es-reporter-viruses kubernetes.io/change-cause="Update to ${CI_COMMIT_TAG}"
    - kubectl apply -f k8s-manifests/amqp-reporting/deployment-smtp.yaml
    - kubectl annotate deployment amqp-smtp-reporter-bacteria kubernetes.io/change-cause="Update to ${CI_COMMIT_TAG}"
    - kubectl annotate deployment amqp-smtp-reporter-metazoa kubernetes.io/change-cause="Update to ${CI_COMMIT_TAG}"
    - kubectl annotate deployment amqp-smtp-reporter-microbes kubernetes.io/change-cause="Update to ${CI_COMMIT_TAG}"
    - kubectl annotate deployment amqp-smtp-reporter-plants kubernetes.io/change-cause="Update to ${CI_COMMIT_TAG}"
    - kubectl annotate deployment amqp-smtp-reporter-production kubernetes.io/change-cause="Update to ${CI_COMMIT_TAG}"
    - kubectl annotate deployment amqp-smtp-reporter-rapid kubernetes.io/change-cause="Update to ${CI_COMMIT_TAG}"
    - kubectl annotate deployment amqp-smtp-reporter-vert kubernetes.io/change-cause="Update to ${CI_COMMIT_TAG}"
    - kubectl annotate deployment amqp-smtp-reporter-viruses kubernetes.io/change-cause="Update to ${CI_COMMIT_TAG}"


deploy_prod:
  extends: .deploy

  only:
    - /^release-.+$/

  except:
    - branches

  environment:
    name: prod


deploy_dev:
  extends: .deploy

  only:
    - tags

  environment:
    name: dev

  before_script:
    - git clone https://oauth2:${GITLAB_ACCESS_TOKEN}@${GITLAB_HOST}/${MANIFESTS_NAMESPACE}/k8s-manifests.git
    - cd k8s-manifests
    - git checkout dev
    - cd ..
