language: python
python:
  - "3.7.9"
  - "3.8.9"

services:
  - docker

before_script:
  - docker-compose -f tests/docker-compose.yml up -d
  - pip install -r requirements-test.txt
  - pip install .

script:
  - coverage run -m pytest tests
  - coverage report -m

after_script:
  - docker-compose -f tests/docker-compose.yml down
