language: python
python:
  - "3.8"

services:
  - docker

before_script:
  - docker-compose -f src/tests/docker-compose.yml up -d
  - pip install -r requirements-test.txt
  - pip install .

script:
  - coverage run -m pytest src/tests
  - coverage report -m

after_script:
  - docker-compose -f src/tests/docker-compose.yml down
