language: python
python:
  - "3.8"

# sudo: required

services:
  - docker

# before_install:
#   - sudo rm /usr/local/bin/docker-compose
#   - pip install docker-compose

before_script:
  - docker-compose -f tests/docker-compose.yml up -d
  - pip install -r requirements-test.txt
  - pip install .

script:
  - coverage run -m pytest tests
  - coverage report -m

after_script:
  - docker-compose -f tests/docker-compose.yml down
