language: python
python:
  - "3.8"

sudo: required

services:
  - docker

before_install:
  - sudo rm /usr/local/bin/docker-compose
  # - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
  # - chmod +x docker-compose
  # - sudo mv docker-compose /usr/local/bin
  - pip install 'docker-compose==1.29.1'

before_script:
  - docker-compose -f tests/docker-compose.yml up -d
  - pip install -r requirements-test.txt
  - pip install .

script:
  - coverage run -m pytest tests
  - coverage report -m

after_script:
  - docker-compose -f tests/docker-compose.yml down
